[package]
name = "moore-circt"
version = "0.14.0"
authors = ["Fabian Schuiki <fabian@schuiki.ch>"]
edition = "2018"

[dependencies]
moore-circt-sys = { path = "../circt-sys", version = "0.14.0" }
num = "0.3"
